# Autostart necessary processes (like notifications daemons, status bars, etc.)
# Or execute your favorite apps at launch like this:

# Luces RGB de los perifericos
exec-once = openrgb -p Logitech

# Fondo de pantalla
exec-once = waypaper --restore
exec-once = swww-daemon && swww img $(cat ~/.config/waypaper/config.ini | grep wallpaper | cut -d= -f2 | xargs) --transition-type none

# Portapapeles (guarda historial incluyendo imágenes)
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store

# Noctalia Shell
exec-once = qs -c noctalia-shell