# See https://wiki.hypr.land/Configuring/Keywords/

# Set programs that you use
$terminal = foot
$fileManager = nautilus
$menu = rofi -show drun -show-icons -icon-theme "WhiteSur-dark"
$editor = vscodium
$browser = brave
$cursorTheme = WhiteSur-cursors
$cursorSize = 24
$profileRGB = Logitech